// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: adventurers.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAdventurerActivities = `-- name: GetAdventurerActivities :many
SELECT 
ah.id,
ah.occurred_at,
ah.activity,
a.name
FROM adventurer_history ah
JOIN adventurers a ON ah.adventurer_id = a.id
WHERE a.id = $1
ORDER BY ah.occurred_at DESC
`

type GetAdventurerActivitiesRow struct {
	ID         uuid.UUID        `json:"id"`
	OccurredAt pgtype.Timestamp `json:"occurred_at"`
	Activity   ActivityEnum     `json:"activity"`
	Name       pgtype.Text      `json:"name"`
}

func (q *Queries) GetAdventurerActivities(ctx context.Context, id uuid.UUID) ([]GetAdventurerActivitiesRow, error) {
	rows, err := q.db.Query(ctx, getAdventurerActivities, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdventurerActivitiesRow
	for rows.Next() {
		var i GetAdventurerActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Activity,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdventurerContractHistory = `-- name: GetAdventurerContractHistory :many
SELECT
a.id AS adventurer_id,
a.name,
c.id AS contract_id,
c.title,
c.contract_status
FROM adventurer_contract_history ach
JOIN adventurers a ON ach.adventurer_id = a.id
JOIN contracts c ON ach.contract_id = c.id
WHERE a.id = $1
ORDER BY ach.occurred_at DESC
`

type GetAdventurerContractHistoryRow struct {
	AdventurerID   uuid.UUID          `json:"adventurer_id"`
	Name           pgtype.Text        `json:"name"`
	ContractID     uuid.UUID          `json:"contract_id"`
	Title          pgtype.Text        `json:"title"`
	ContractStatus ContractStatusEnum `json:"contract_status"`
}

func (q *Queries) GetAdventurerContractHistory(ctx context.Context, id uuid.UUID) ([]GetAdventurerContractHistoryRow, error) {
	rows, err := q.db.Query(ctx, getAdventurerContractHistory, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdventurerContractHistoryRow
	for rows.Next() {
		var i GetAdventurerContractHistoryRow
		if err := rows.Scan(
			&i.AdventurerID,
			&i.Name,
			&i.ContractID,
			&i.Title,
			&i.ContractStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdventurerDetails = `-- name: GetAdventurerDetails :one
SELECT
id,
name,
current_rank,
role,
current_activity,
recruitment_cost
FROM adventurers
WHERE id = $1
`

type GetAdventurerDetailsRow struct {
	ID              uuid.UUID    `json:"id"`
	Name            pgtype.Text  `json:"name"`
	CurrentRank     RankEnum     `json:"current_rank"`
	Role            RoleEnum     `json:"role"`
	CurrentActivity ActivityEnum `json:"current_activity"`
	RecruitmentCost int32        `json:"recruitment_cost"`
}

func (q *Queries) GetAdventurerDetails(ctx context.Context, id uuid.UUID) (GetAdventurerDetailsRow, error) {
	row := q.db.QueryRow(ctx, getAdventurerDetails, id)
	var i GetAdventurerDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrentRank,
		&i.Role,
		&i.CurrentActivity,
		&i.RecruitmentCost,
	)
	return i, err
}

const getAdventurerUpkeepCost = `-- name: GetAdventurerUpkeepCost :exec
SELECT
upkeep_cost
FROM adventurers
WHERE id = $1
`

func (q *Queries) GetAdventurerUpkeepCost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, getAdventurerUpkeepCost, id)
	return err
}

const getAdventurers = `-- name: GetAdventurers :many
SELECT 
id,
joined_at,
current_rank,
current_activity,
description,
name,
role
FROM adventurers
WHERE guild_id = $1
ORDER BY
	CASE WHEN $2::text = 'joined_at' THEN joined_at END ASC,
	CASE WHEN $2::text = 'name' THEN name END ASC,
	CASE WHEN $2::text = 'role' THEN role END ASC,
	CASE WHEN $2::text = 'activity' THEN current_activity END ASC
`

type GetAdventurersParams struct {
	GuildID pgtype.UUID `json:"guild_id"`
	SortBy  string      `json:"sort_by"`
}

type GetAdventurersRow struct {
	ID              uuid.UUID        `json:"id"`
	JoinedAt        pgtype.Timestamp `json:"joined_at"`
	CurrentRank     RankEnum         `json:"current_rank"`
	CurrentActivity ActivityEnum     `json:"current_activity"`
	Description     string           `json:"description"`
	Name            pgtype.Text      `json:"name"`
	Role            RoleEnum         `json:"role"`
}

func (q *Queries) GetAdventurers(ctx context.Context, arg GetAdventurersParams) ([]GetAdventurersRow, error) {
	rows, err := q.db.Query(ctx, getAdventurers, arg.GuildID, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdventurersRow
	for rows.Next() {
		var i GetAdventurersRow
		if err := rows.Scan(
			&i.ID,
			&i.JoinedAt,
			&i.CurrentRank,
			&i.CurrentActivity,
			&i.Description,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdventurersByGuild = `-- name: GetAdventurersByGuild :many
SELECT
id,
name,
current_rank,
role,
description,
current_activity
FROM adventurers
WHERE guild_id = $1
`

type GetAdventurersByGuildRow struct {
	ID              uuid.UUID    `json:"id"`
	Name            pgtype.Text  `json:"name"`
	CurrentRank     RankEnum     `json:"current_rank"`
	Role            RoleEnum     `json:"role"`
	Description     string       `json:"description"`
	CurrentActivity ActivityEnum `json:"current_activity"`
}

func (q *Queries) GetAdventurersByGuild(ctx context.Context, guildID pgtype.UUID) ([]GetAdventurersByGuildRow, error) {
	rows, err := q.db.Query(ctx, getAdventurersByGuild, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdventurersByGuildRow
	for rows.Next() {
		var i GetAdventurersByGuildRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CurrentRank,
			&i.Role,
			&i.Description,
			&i.CurrentActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdventurersWithRole = `-- name: GetAdventurersWithRole :many
SELECT 
id,
joined_at,
current_rank,
current_activity,
name,
description,
role 
FROM adventurers
WHERE guild_id = $1 AND role = $2
ORDER BY
	CASE WHEN $3::text = 'joined_at' THEN joined_at END ASC,
	CASE WHEN $3::text = 'name' THEN name END ASC,
	CASE WHEN $3::text = 'activity' THEN current_activity END ASC
`

type GetAdventurersWithRoleParams struct {
	GuildID pgtype.UUID `json:"guild_id"`
	Role    RoleEnum    `json:"role"`
	SortBy  string      `json:"sort_by"`
}

type GetAdventurersWithRoleRow struct {
	ID              uuid.UUID        `json:"id"`
	JoinedAt        pgtype.Timestamp `json:"joined_at"`
	CurrentRank     RankEnum         `json:"current_rank"`
	CurrentActivity ActivityEnum     `json:"current_activity"`
	Name            pgtype.Text      `json:"name"`
	Description     string           `json:"description"`
	Role            RoleEnum         `json:"role"`
}

func (q *Queries) GetAdventurersWithRole(ctx context.Context, arg GetAdventurersWithRoleParams) ([]GetAdventurersWithRoleRow, error) {
	rows, err := q.db.Query(ctx, getAdventurersWithRole, arg.GuildID, arg.Role, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdventurersWithRoleRow
	for rows.Next() {
		var i GetAdventurersWithRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.JoinedAt,
			&i.CurrentRank,
			&i.CurrentActivity,
			&i.Name,
			&i.Description,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdventurersWithStatus = `-- name: GetAdventurersWithStatus :many
SELECT 
id,
joined_at,
current_rank,
current_activity,
description,
name,
role
FROM adventurers 
WHERE guild_id = $1 AND current_activity = $2
ORDER BY
	CASE WHEN $3::text = 'joined_at' THEN joined_at END ASC,
	CASE WHEN $3::text = 'name' THEN name END ASC,
	CASE WHEN $3::text = 'role' THEN role END ASC
`

type GetAdventurersWithStatusParams struct {
	GuildID         pgtype.UUID  `json:"guild_id"`
	CurrentActivity ActivityEnum `json:"current_activity"`
	SortBy          string       `json:"sort_by"`
}

type GetAdventurersWithStatusRow struct {
	ID              uuid.UUID        `json:"id"`
	JoinedAt        pgtype.Timestamp `json:"joined_at"`
	CurrentRank     RankEnum         `json:"current_rank"`
	CurrentActivity ActivityEnum     `json:"current_activity"`
	Description     string           `json:"description"`
	Name            pgtype.Text      `json:"name"`
	Role            RoleEnum         `json:"role"`
}

func (q *Queries) GetAdventurersWithStatus(ctx context.Context, arg GetAdventurersWithStatusParams) ([]GetAdventurersWithStatusRow, error) {
	rows, err := q.db.Query(ctx, getAdventurersWithStatus, arg.GuildID, arg.CurrentActivity, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdventurersWithStatusRow
	for rows.Next() {
		var i GetAdventurersWithStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.JoinedAt,
			&i.CurrentRank,
			&i.CurrentActivity,
			&i.Description,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecruitableAdventurers = `-- name: GetRecruitableAdventurers :many
SELECT 
id,
name,
role,
description,
current_rank
FROM adventurers
WHERE guild_id IS NULL
ORDER BY
	CASE WHEN $1::text = 'joined_at' THEN joined_at END ASC,
	CASE WHEN $1::text = 'name' THEN name END ASC,
	CASE WHEN $1::text = 'role' THEN role END ASC,
	CASE WHEN $1::text = 'status' THEN role END ASC
`

type GetRecruitableAdventurersRow struct {
	ID          uuid.UUID   `json:"id"`
	Name        pgtype.Text `json:"name"`
	Role        RoleEnum    `json:"role"`
	Description string      `json:"description"`
	CurrentRank RankEnum    `json:"current_rank"`
}

func (q *Queries) GetRecruitableAdventurers(ctx context.Context, sortBy string) ([]GetRecruitableAdventurersRow, error) {
	rows, err := q.db.Query(ctx, getRecruitableAdventurers, sortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecruitableAdventurersRow
	for rows.Next() {
		var i GetRecruitableAdventurersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Description,
			&i.CurrentRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAdventurerContractHistory = `-- name: InsertAdventurerContractHistory :exec
INSERT INTO adventurer_contract_history(
	adventurer_id,
	contract_id,
	status
) VALUES($1, $2, $3)
`

type InsertAdventurerContractHistoryParams struct {
	AdventurerID uuid.UUID          `json:"adventurer_id"`
	ContractID   uuid.UUID          `json:"contract_id"`
	Status       ContractStatusEnum `json:"status"`
}

func (q *Queries) InsertAdventurerContractHistory(ctx context.Context, arg InsertAdventurerContractHistoryParams) error {
	_, err := q.db.Exec(ctx, insertAdventurerContractHistory, arg.AdventurerID, arg.ContractID, arg.Status)
	return err
}

const insertAdventurerHistory = `-- name: InsertAdventurerHistory :exec
INSERT INTO adventurer_history(
adventurer_id,
activity
)VALUES($1, $2)
`

type InsertAdventurerHistoryParams struct {
	AdventurerID uuid.UUID    `json:"adventurer_id"`
	Activity     ActivityEnum `json:"activity"`
}

func (q *Queries) InsertAdventurerHistory(ctx context.Context, arg InsertAdventurerHistoryParams) error {
	_, err := q.db.Exec(ctx, insertAdventurerHistory, arg.AdventurerID, arg.Activity)
	return err
}

const setAdventurerActivity = `-- name: SetAdventurerActivity :exec
UPDATE adventurers
SET current_activity = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type SetAdventurerActivityParams struct {
	CurrentActivity ActivityEnum `json:"current_activity"`
	ID              uuid.UUID    `json:"id"`
}

func (q *Queries) SetAdventurerActivity(ctx context.Context, arg SetAdventurerActivityParams) error {
	_, err := q.db.Exec(ctx, setAdventurerActivity, arg.CurrentActivity, arg.ID)
	return err
}

const setAdventurerHired = `-- name: SetAdventurerHired :exec
UPDATE adventurers
SET guild_id = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type SetAdventurerHiredParams struct {
	GuildID pgtype.UUID `json:"guild_id"`
	ID      uuid.UUID   `json:"id"`
}

func (q *Queries) SetAdventurerHired(ctx context.Context, arg SetAdventurerHiredParams) error {
	_, err := q.db.Exec(ctx, setAdventurerHired, arg.GuildID, arg.ID)
	return err
}

const setAdventurerRank = `-- name: SetAdventurerRank :exec
UPDATE adventurers
SET current_rank = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type SetAdventurerRankParams struct {
	CurrentRank RankEnum  `json:"current_rank"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) SetAdventurerRank(ctx context.Context, arg SetAdventurerRankParams) error {
	_, err := q.db.Exec(ctx, setAdventurerRank, arg.CurrentRank, arg.ID)
	return err
}

const upsertAdventurer = `-- name: UpsertAdventurer :one
Insert INTO adventurers(name, current_rank, role, description)
VALUES($1, $2, $3, $4)
RETURNING id, guild_id, party_id, joined_at, updated_at, current_rank, current_activity, name, description, role, upkeep_cost, recruitment_cost
`

type UpsertAdventurerParams struct {
	Name        pgtype.Text `json:"name"`
	CurrentRank RankEnum    `json:"current_rank"`
	Role        RoleEnum    `json:"role"`
	Description string      `json:"description"`
}

func (q *Queries) UpsertAdventurer(ctx context.Context, arg UpsertAdventurerParams) (Adventurer, error) {
	row := q.db.QueryRow(ctx, upsertAdventurer,
		arg.Name,
		arg.CurrentRank,
		arg.Role,
		arg.Description,
	)
	var i Adventurer
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.PartyID,
		&i.JoinedAt,
		&i.UpdatedAt,
		&i.CurrentRank,
		&i.CurrentActivity,
		&i.Name,
		&i.Description,
		&i.Role,
		&i.UpkeepCost,
		&i.RecruitmentCost,
	)
	return i, err
}
