// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contracts.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignToGuild = `-- name: AssignToGuild :exec
UPDATE contracts
SET guild_id = $2
WHERE id = $1
`

type AssignToGuildParams struct {
	ID      uuid.UUID   `json:"id"`
	GuildID pgtype.UUID `json:"guild_id"`
}

func (q *Queries) AssignToGuild(ctx context.Context, arg AssignToGuildParams) error {
	_, err := q.db.Exec(ctx, assignToGuild, arg.ID, arg.GuildID)
	return err
}

const countPartyCompleteContracts = `-- name: CountPartyCompleteContracts :one
SELECT COUNT(*)
FROM party_history ph
JOIN contracts c ON ph.contract_id = c.id
JOIN parties p ON ph.party_id = p.id
WHERE ph.party_id = $1 
AND ph.contract_status = 'complete'
AND c.difficulty >= p.party_rank
`

func (q *Queries) CountPartyCompleteContracts(ctx context.Context, partyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPartyCompleteContracts, partyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getContractByID = `-- name: GetContractByID :one
SELECT
id,
guild_id,
difficulty,
description,
minimum_party_size,
contract_status
FROM contracts
WHERE id = $1
`

type GetContractByIDRow struct {
	ID               uuid.UUID          `json:"id"`
	GuildID          pgtype.UUID        `json:"guild_id"`
	Difficulty       int32              `json:"difficulty"`
	Description      pgtype.Text        `json:"description"`
	MinimumPartySize int32              `json:"minimum_party_size"`
	ContractStatus   ContractStatusEnum `json:"contract_status"`
}

func (q *Queries) GetContractByID(ctx context.Context, id uuid.UUID) (GetContractByIDRow, error) {
	row := q.db.QueryRow(ctx, getContractByID, id)
	var i GetContractByIDRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Difficulty,
		&i.Description,
		&i.MinimumPartySize,
		&i.ContractStatus,
	)
	return i, err
}

const getPartyOnContract = `-- name: GetPartyOnContract :one
SELECT
id,
name,
party_rank
FROM parties
WHERE contract_id = $1
`

type GetPartyOnContractRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	PartyRank int32     `json:"party_rank"`
}

func (q *Queries) GetPartyOnContract(ctx context.Context, contractID pgtype.UUID) (GetPartyOnContractRow, error) {
	row := q.db.QueryRow(ctx, getPartyOnContract, contractID)
	var i GetPartyOnContractRow
	err := row.Scan(&i.ID, &i.Name, &i.PartyRank)
	return i, err
}

const listAvailableContracts = `-- name: ListAvailableContracts :many
SELECT
id,
title,
difficulty,
minimum_party_size,
contract_status
FROM contracts
WHERE guild_id IS NULL
ORDER BY
    CASE WHEN $1::text = 'title' THEN title END ASC,
    CASE WHEN $1::text = 'difficulty' THEN difficulty END ASC,
    CASE WHEN $1::text = 'contract_status' THEN contract_status END ASC,
    CASE WHEN $1::text = 'minimum_party_size' THEN minimum_party_size END ASC
`

type ListAvailableContractsRow struct {
	ID               uuid.UUID          `json:"id"`
	Title            pgtype.Text        `json:"title"`
	Difficulty       int32              `json:"difficulty"`
	MinimumPartySize int32              `json:"minimum_party_size"`
	ContractStatus   ContractStatusEnum `json:"contract_status"`
}

func (q *Queries) ListAvailableContracts(ctx context.Context, sortBy string) ([]ListAvailableContractsRow, error) {
	rows, err := q.db.Query(ctx, listAvailableContracts, sortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableContractsRow
	for rows.Next() {
		var i ListAvailableContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Difficulty,
			&i.MinimumPartySize,
			&i.ContractStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractsWithMaxDifficulty = `-- name: ListContractsWithMaxDifficulty :many
SELECT
id,
title,
difficulty,
minimum_party_size,
contract_status
FROM contracts
WHERE difficulty <= $1 AND guild_id = $2
ORDER BY
    CASE WHEN $3::text = 'title' THEN title END ASC,
    CASE WHEN $3::text = 'difficulty' THEN difficulty END ASC,
    CASE WHEN $3::text = 'contract_status' THEN contract_status END ASC,
    CASE WHEN $3::text = 'minimum_party_size' THEN minimum_party_size END ASC
`

type ListContractsWithMaxDifficultyParams struct {
	Difficulty int32       `json:"difficulty"`
	GuildID    pgtype.UUID `json:"guild_id"`
	SortBy     string      `json:"sort_by"`
}

type ListContractsWithMaxDifficultyRow struct {
	ID               uuid.UUID          `json:"id"`
	Title            pgtype.Text        `json:"title"`
	Difficulty       int32              `json:"difficulty"`
	MinimumPartySize int32              `json:"minimum_party_size"`
	ContractStatus   ContractStatusEnum `json:"contract_status"`
}

func (q *Queries) ListContractsWithMaxDifficulty(ctx context.Context, arg ListContractsWithMaxDifficultyParams) ([]ListContractsWithMaxDifficultyRow, error) {
	rows, err := q.db.Query(ctx, listContractsWithMaxDifficulty, arg.Difficulty, arg.GuildID, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContractsWithMaxDifficultyRow
	for rows.Next() {
		var i ListContractsWithMaxDifficultyRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Difficulty,
			&i.MinimumPartySize,
			&i.ContractStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractsWithMaxPartySize = `-- name: ListContractsWithMaxPartySize :many
SELECT
id,
title,
difficulty,
minimum_party_size,
contract_status
FROM contracts
WHERE minimum_party_size <= $1 AND guild_id = $2
ORDER BY
    CASE WHEN $3::text = 'title' THEN title END ASC,
    CASE WHEN $3::text = 'difficulty' THEN difficulty END ASC,
    CASE WHEN $3::text = 'contract_status' THEN contract_status END ASC,
    CASE WHEN $3::text = 'minimum_party_size' THEN minimum_party_size END ASC
`

type ListContractsWithMaxPartySizeParams struct {
	MinimumPartySize int32       `json:"minimum_party_size"`
	GuildID          pgtype.UUID `json:"guild_id"`
	SortBy           string      `json:"sort_by"`
}

type ListContractsWithMaxPartySizeRow struct {
	ID               uuid.UUID          `json:"id"`
	Title            pgtype.Text        `json:"title"`
	Difficulty       int32              `json:"difficulty"`
	MinimumPartySize int32              `json:"minimum_party_size"`
	ContractStatus   ContractStatusEnum `json:"contract_status"`
}

func (q *Queries) ListContractsWithMaxPartySize(ctx context.Context, arg ListContractsWithMaxPartySizeParams) ([]ListContractsWithMaxPartySizeRow, error) {
	rows, err := q.db.Query(ctx, listContractsWithMaxPartySize, arg.MinimumPartySize, arg.GuildID, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContractsWithMaxPartySizeRow
	for rows.Next() {
		var i ListContractsWithMaxPartySizeRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Difficulty,
			&i.MinimumPartySize,
			&i.ContractStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractsWithMinDifficulty = `-- name: ListContractsWithMinDifficulty :many
SELECT
id,
title,
difficulty,
minimum_party_size,
contract_status
FROM contracts
WHERE difficulty >= $1 AND guild_id = $2
ORDER BY
    CASE WHEN $3::text = 'title' THEN title END ASC,
    CASE WHEN $3::text = 'difficulty' THEN difficulty END ASC,
    CASE WHEN $3::text = 'contract_status' THEN contract_status END ASC,
    CASE WHEN $3::text = 'minimum_party_size' THEN minimum_party_size END ASC
`

type ListContractsWithMinDifficultyParams struct {
	Difficulty int32       `json:"difficulty"`
	GuildID    pgtype.UUID `json:"guild_id"`
	SortBy     string      `json:"sort_by"`
}

type ListContractsWithMinDifficultyRow struct {
	ID               uuid.UUID          `json:"id"`
	Title            pgtype.Text        `json:"title"`
	Difficulty       int32              `json:"difficulty"`
	MinimumPartySize int32              `json:"minimum_party_size"`
	ContractStatus   ContractStatusEnum `json:"contract_status"`
}

func (q *Queries) ListContractsWithMinDifficulty(ctx context.Context, arg ListContractsWithMinDifficultyParams) ([]ListContractsWithMinDifficultyRow, error) {
	rows, err := q.db.Query(ctx, listContractsWithMinDifficulty, arg.Difficulty, arg.GuildID, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContractsWithMinDifficultyRow
	for rows.Next() {
		var i ListContractsWithMinDifficultyRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Difficulty,
			&i.MinimumPartySize,
			&i.ContractStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractsWithMinPartySize = `-- name: ListContractsWithMinPartySize :many
SELECT
id,
title,
difficulty,
minimum_party_size,
contract_status
FROM contracts
WHERE minimum_party_size >= $1 AND guild_id = $2
ORDER BY
    CASE WHEN $3::text = 'title' THEN title END ASC,
    CASE WHEN $3::text = 'difficulty' THEN difficulty END ASC,
    CASE WHEN $3::text = 'contract_status' THEN contract_status END ASC,
    CASE WHEN $3::text = 'minimum_party_size' THEN minimum_party_size END ASC
`

type ListContractsWithMinPartySizeParams struct {
	MinimumPartySize int32       `json:"minimum_party_size"`
	GuildID          pgtype.UUID `json:"guild_id"`
	SortBy           string      `json:"sort_by"`
}

type ListContractsWithMinPartySizeRow struct {
	ID               uuid.UUID          `json:"id"`
	Title            pgtype.Text        `json:"title"`
	Difficulty       int32              `json:"difficulty"`
	MinimumPartySize int32              `json:"minimum_party_size"`
	ContractStatus   ContractStatusEnum `json:"contract_status"`
}

func (q *Queries) ListContractsWithMinPartySize(ctx context.Context, arg ListContractsWithMinPartySizeParams) ([]ListContractsWithMinPartySizeRow, error) {
	rows, err := q.db.Query(ctx, listContractsWithMinPartySize, arg.MinimumPartySize, arg.GuildID, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContractsWithMinPartySizeRow
	for rows.Next() {
		var i ListContractsWithMinPartySizeRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Difficulty,
			&i.MinimumPartySize,
			&i.ContractStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractsWithStatus = `-- name: ListContractsWithStatus :many
SELECT
id,
title,
difficulty,
minimum_party_size,
contract_status
FROM contracts
WHERE contract_status = $1 AND guild_id = $2
ORDER BY
    CASE WHEN $3::text = 'title' THEN title END ASC,
    CASE WHEN $3::text = 'difficulty' THEN difficulty END ASC,
    CASE WHEN $3::text = 'minimum_party_size' THEN minimum_party_size END ASC
`

type ListContractsWithStatusParams struct {
	ContractStatus ContractStatusEnum `json:"contract_status"`
	GuildID        pgtype.UUID        `json:"guild_id"`
	SortBy         string             `json:"sort_by"`
}

type ListContractsWithStatusRow struct {
	ID               uuid.UUID          `json:"id"`
	Title            pgtype.Text        `json:"title"`
	Difficulty       int32              `json:"difficulty"`
	MinimumPartySize int32              `json:"minimum_party_size"`
	ContractStatus   ContractStatusEnum `json:"contract_status"`
}

func (q *Queries) ListContractsWithStatus(ctx context.Context, arg ListContractsWithStatusParams) ([]ListContractsWithStatusRow, error) {
	rows, err := q.db.Query(ctx, listContractsWithStatus, arg.ContractStatus, arg.GuildID, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContractsWithStatusRow
	for rows.Next() {
		var i ListContractsWithStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Difficulty,
			&i.MinimumPartySize,
			&i.ContractStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setContractStatus = `-- name: SetContractStatus :exec
UPDATE contracts
SET contract_status = $2
WHERE id = $1 AND guild_id = $3
`

type SetContractStatusParams struct {
	ID             uuid.UUID          `json:"id"`
	ContractStatus ContractStatusEnum `json:"contract_status"`
	GuildID        pgtype.UUID        `json:"guild_id"`
}

func (q *Queries) SetContractStatus(ctx context.Context, arg SetContractStatusParams) error {
	_, err := q.db.Exec(ctx, setContractStatus, arg.ID, arg.ContractStatus, arg.GuildID)
	return err
}
