// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contracts.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPartyOnContract = `-- name: GetPartyOnContract :many
SELECT
p.id AS party_id,
a.id AS adventurer_id,
a.name,
a.current_rank,
a.role
FROM contracts c
JOIN parties p ON c.id = p.contract_id
JOIN party_members pm ON p.id = pm.party_id
JOIN adventurers a ON pm.adventurer_id = a.id
WHERE c.id = $1
`

type GetPartyOnContractRow struct {
	PartyID      uuid.UUID   `json:"party_id"`
	AdventurerID uuid.UUID   `json:"adventurer_id"`
	Name         pgtype.Text `json:"name"`
	CurrentRank  RankEnum    `json:"current_rank"`
	Role         RoleEnum    `json:"role"`
}

func (q *Queries) GetPartyOnContract(ctx context.Context, id uuid.UUID) ([]GetPartyOnContractRow, error) {
	rows, err := q.db.Query(ctx, getPartyOnContract, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPartyOnContractRow
	for rows.Next() {
		var i GetPartyOnContractRow
		if err := rows.Scan(
			&i.PartyID,
			&i.AdventurerID,
			&i.Name,
			&i.CurrentRank,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPastContractsWithStatus = `-- name: GetPastContractsWithStatus :many
SELECT 
ch.id AS contract_history_id,
ch.guild_id,
ch.contract_id,
c.title,
ch.occurred_at,
ch.status,
c.difficulty
FROM contract_history ch
JOIN contracts c ON ch.contract_id = c.id
WHERE ch.status = $1
ORDER BY
	CASE WHEN $2::text = 'title' THEN title END ASC,
	CASE WHEN $2::text = 'difficulty' THEN difficulty END ASC,
	CASE WHEN $2::text = 
		'minimum_party_size' THEN minimum_party_size END ASC
`

type GetPastContractsWithStatusParams struct {
	Status ContractStatusEnum `json:"status"`
	SortBy string             `json:"sort_by"`
}

type GetPastContractsWithStatusRow struct {
	ContractHistoryID uuid.UUID          `json:"contract_history_id"`
	GuildID           uuid.UUID          `json:"guild_id"`
	ContractID        uuid.UUID          `json:"contract_id"`
	Title             pgtype.Text        `json:"title"`
	OccurredAt        pgtype.Timestamp   `json:"occurred_at"`
	Status            ContractStatusEnum `json:"status"`
	Difficulty        int32              `json:"difficulty"`
}

func (q *Queries) GetPastContractsWithStatus(ctx context.Context, arg GetPastContractsWithStatusParams) ([]GetPastContractsWithStatusRow, error) {
	rows, err := q.db.Query(ctx, getPastContractsWithStatus, arg.Status, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPastContractsWithStatusRow
	for rows.Next() {
		var i GetPastContractsWithStatusRow
		if err := rows.Scan(
			&i.ContractHistoryID,
			&i.GuildID,
			&i.ContractID,
			&i.Title,
			&i.OccurredAt,
			&i.Status,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertContractHistory = `-- name: InsertContractHistory :exec
INSERT INTO contract_history (
guild_id,
contract_id,
status
) VALUES ($1, $2, $3)
`

type InsertContractHistoryParams struct {
	GuildID    uuid.UUID          `json:"guild_id"`
	ContractID uuid.UUID          `json:"contract_id"`
	Status     ContractStatusEnum `json:"status"`
}

func (q *Queries) InsertContractHistory(ctx context.Context, arg InsertContractHistoryParams) error {
	_, err := q.db.Exec(ctx, insertContractHistory, arg.GuildID, arg.ContractID, arg.Status)
	return err
}

const listContracts = `-- name: ListContracts :many
SELECT
    id,
    guild_id,
    title,
    difficulty,
    minimum_party_size,
    contract_status
FROM contracts
WHERE 
    ($1::int IS NULL OR difficulty = $1) AND
    ($2::int IS NULL OR minimum_party_size >= $2) AND
    ($3::contract_status_enum IS NULL OR contract_status = $3)
ORDER BY
    CASE WHEN $4::text = 'title' THEN title END ASC,
    CASE WHEN $4::text = 'difficulty' THEN difficulty END ASC,
    CASE WHEN $4::text = 'contract_status' THEN contract_status END ASC,
    CASE WHEN $4::text = 'minimum_party_size' THEN minimum_party_size END ASC
`

type ListContractsParams struct {
	Difficulty   pgtype.Int4            `json:"difficulty"`
	MinPartySize pgtype.Int4            `json:"min_party_size"`
	Status       NullContractStatusEnum `json:"status"`
	SortBy       string                 `json:"sort_by"`
}

type ListContractsRow struct {
	ID               uuid.UUID          `json:"id"`
	GuildID          uuid.UUID          `json:"guild_id"`
	Title            pgtype.Text        `json:"title"`
	Difficulty       int32              `json:"difficulty"`
	MinimumPartySize int32              `json:"minimum_party_size"`
	ContractStatus   ContractStatusEnum `json:"contract_status"`
}

func (q *Queries) ListContracts(ctx context.Context, arg ListContractsParams) ([]ListContractsRow, error) {
	rows, err := q.db.Query(ctx, listContracts,
		arg.Difficulty,
		arg.MinPartySize,
		arg.Status,
		arg.SortBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContractsRow
	for rows.Next() {
		var i ListContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Title,
			&i.Difficulty,
			&i.MinimumPartySize,
			&i.ContractStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setContractStatus = `-- name: SetContractStatus :exec
UPDATE contracts
SET party_id = NULL, contract_status = $2
WHERE id = $1
`

type SetContractStatusParams struct {
	ID             uuid.UUID          `json:"id"`
	ContractStatus ContractStatusEnum `json:"contract_status"`
}

func (q *Queries) SetContractStatus(ctx context.Context, arg SetContractStatusParams) error {
	_, err := q.db.Exec(ctx, setContractStatus, arg.ID, arg.ContractStatus)
	return err
}
