// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contract_history.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getHistoryOfContract = `-- name: GetHistoryOfContract :many
SELECT
ch.id AS contract_history_id,
g.name AS guild_name,
p.name AS party_name,
ch.contract_id,
c.title,
ch.occurred_at,
ch.status,
ch.difficulty
FROM contract_history ch
JOIN contracts c ON ch.contract_id = c.id
JOIN guilds g ON ch.guild_id = g.id
JOIN parties p ON ch.party_id = p.id
WHERE ch.contract_id = $1 AND ch.guild_id = $2
`

type GetHistoryOfContractParams struct {
	ContractID uuid.UUID `json:"contract_id"`
	GuildID    uuid.UUID `json:"guild_id"`
}

type GetHistoryOfContractRow struct {
	ContractHistoryID uuid.UUID          `json:"contract_history_id"`
	GuildName         string             `json:"guild_name"`
	PartyName         string             `json:"party_name"`
	ContractID        uuid.UUID          `json:"contract_id"`
	Title             pgtype.Text        `json:"title"`
	OccurredAt        pgtype.Timestamp   `json:"occurred_at"`
	Status            ContractStatusEnum `json:"status"`
	Difficulty        int32              `json:"difficulty"`
}

func (q *Queries) GetHistoryOfContract(ctx context.Context, arg GetHistoryOfContractParams) ([]GetHistoryOfContractRow, error) {
	rows, err := q.db.Query(ctx, getHistoryOfContract, arg.ContractID, arg.GuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHistoryOfContractRow
	for rows.Next() {
		var i GetHistoryOfContractRow
		if err := rows.Scan(
			&i.ContractHistoryID,
			&i.GuildName,
			&i.PartyName,
			&i.ContractID,
			&i.Title,
			&i.OccurredAt,
			&i.Status,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartyContractHistory = `-- name: GetPartyContractHistory :many
SELECT 
ch.id AS contract_history_id,
c.title,
p.name,
p.party_rank,
ch.occurred_at,
ch.difficulty,
ch.status
FROM contract_history ch
JOIN contracts c ON ch.contract_id = c.id
JOIN parties p ON ch.party_id = p.id
WHERE p.id = $1 AND ch.guild_id = $2
`

type GetPartyContractHistoryParams struct {
	ID      uuid.UUID `json:"id"`
	GuildID uuid.UUID `json:"guild_id"`
}

type GetPartyContractHistoryRow struct {
	ContractHistoryID uuid.UUID          `json:"contract_history_id"`
	Title             pgtype.Text        `json:"title"`
	Name              string             `json:"name"`
	PartyRank         int32              `json:"party_rank"`
	OccurredAt        pgtype.Timestamp   `json:"occurred_at"`
	Difficulty        int32              `json:"difficulty"`
	Status            ContractStatusEnum `json:"status"`
}

func (q *Queries) GetPartyContractHistory(ctx context.Context, arg GetPartyContractHistoryParams) ([]GetPartyContractHistoryRow, error) {
	rows, err := q.db.Query(ctx, getPartyContractHistory, arg.ID, arg.GuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPartyContractHistoryRow
	for rows.Next() {
		var i GetPartyContractHistoryRow
		if err := rows.Scan(
			&i.ContractHistoryID,
			&i.Title,
			&i.Name,
			&i.PartyRank,
			&i.OccurredAt,
			&i.Difficulty,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPastContractsMaxDifficulty = `-- name: GetPastContractsMaxDifficulty :many
SELECT 
ch.id AS contract_history_id,
ch.guild_id,
ch.contract_id,
c.title,
ch.occurred_at,
ch.status,
c.difficulty
FROM contract_history ch
JOIN contracts c ON ch.contract_id = c.id
WHERE ch.difficulty <= $1 AND ch.guild_id = $2
ORDER BY
	CASE WHEN $3::text = 'title' THEN title END ASC,
	CASE WHEN $3::text = 'difficulty' THEN difficulty END ASC,
	CASE WHEN $3::text = 
		'rec_party_size' THEN minimum_party_size END ASC
`

type GetPastContractsMaxDifficultyParams struct {
	Difficulty int32     `json:"difficulty"`
	GuildID    uuid.UUID `json:"guild_id"`
	SortBy     string    `json:"sort_by"`
}

type GetPastContractsMaxDifficultyRow struct {
	ContractHistoryID uuid.UUID          `json:"contract_history_id"`
	GuildID           uuid.UUID          `json:"guild_id"`
	ContractID        uuid.UUID          `json:"contract_id"`
	Title             pgtype.Text        `json:"title"`
	OccurredAt        pgtype.Timestamp   `json:"occurred_at"`
	Status            ContractStatusEnum `json:"status"`
	Difficulty        int32              `json:"difficulty"`
}

func (q *Queries) GetPastContractsMaxDifficulty(ctx context.Context, arg GetPastContractsMaxDifficultyParams) ([]GetPastContractsMaxDifficultyRow, error) {
	rows, err := q.db.Query(ctx, getPastContractsMaxDifficulty, arg.Difficulty, arg.GuildID, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPastContractsMaxDifficultyRow
	for rows.Next() {
		var i GetPastContractsMaxDifficultyRow
		if err := rows.Scan(
			&i.ContractHistoryID,
			&i.GuildID,
			&i.ContractID,
			&i.Title,
			&i.OccurredAt,
			&i.Status,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPastContractsMinDifficulty = `-- name: GetPastContractsMinDifficulty :many
SELECT 
ch.id AS contract_history_id,
ch.guild_id,
ch.contract_id,
c.title,
ch.occurred_at,
ch.status,
c.difficulty
FROM contract_history ch
JOIN contracts c ON ch.contract_id = c.id
WHERE ch.difficulty >= $1 AND ch.guild_id = $2
ORDER BY
	CASE WHEN $3::text = 'title' THEN title END ASC,
	CASE WHEN $3::text = 'difficulty' THEN difficulty END ASC,
	CASE WHEN $3::text = 
		'rec_party_size' THEN minimum_party_size END ASC
`

type GetPastContractsMinDifficultyParams struct {
	Difficulty int32     `json:"difficulty"`
	GuildID    uuid.UUID `json:"guild_id"`
	SortBy     string    `json:"sort_by"`
}

type GetPastContractsMinDifficultyRow struct {
	ContractHistoryID uuid.UUID          `json:"contract_history_id"`
	GuildID           uuid.UUID          `json:"guild_id"`
	ContractID        uuid.UUID          `json:"contract_id"`
	Title             pgtype.Text        `json:"title"`
	OccurredAt        pgtype.Timestamp   `json:"occurred_at"`
	Status            ContractStatusEnum `json:"status"`
	Difficulty        int32              `json:"difficulty"`
}

func (q *Queries) GetPastContractsMinDifficulty(ctx context.Context, arg GetPastContractsMinDifficultyParams) ([]GetPastContractsMinDifficultyRow, error) {
	rows, err := q.db.Query(ctx, getPastContractsMinDifficulty, arg.Difficulty, arg.GuildID, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPastContractsMinDifficultyRow
	for rows.Next() {
		var i GetPastContractsMinDifficultyRow
		if err := rows.Scan(
			&i.ContractHistoryID,
			&i.GuildID,
			&i.ContractID,
			&i.Title,
			&i.OccurredAt,
			&i.Status,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPastContractsWithStatus = `-- name: GetPastContractsWithStatus :many
SELECT 
ch.id AS contract_history_id,
ch.guild_id,
ch.contract_id,
c.title,
ch.occurred_at,
ch.status,
c.difficulty
FROM contract_history ch
JOIN contracts c ON ch.contract_id = c.id
WHERE ch.status = $1 AND ch.guild_id = $2
ORDER BY
	CASE WHEN $3::text = 'title' THEN title END ASC,
	CASE WHEN $3::text = 'difficulty' THEN difficulty END ASC,
	CASE WHEN $3::text = 
		'rec_party_size' THEN minimum_party_size END ASC
`

type GetPastContractsWithStatusParams struct {
	Status  ContractStatusEnum `json:"status"`
	GuildID uuid.UUID          `json:"guild_id"`
	SortBy  string             `json:"sort_by"`
}

type GetPastContractsWithStatusRow struct {
	ContractHistoryID uuid.UUID          `json:"contract_history_id"`
	GuildID           uuid.UUID          `json:"guild_id"`
	ContractID        uuid.UUID          `json:"contract_id"`
	Title             pgtype.Text        `json:"title"`
	OccurredAt        pgtype.Timestamp   `json:"occurred_at"`
	Status            ContractStatusEnum `json:"status"`
	Difficulty        int32              `json:"difficulty"`
}

func (q *Queries) GetPastContractsWithStatus(ctx context.Context, arg GetPastContractsWithStatusParams) ([]GetPastContractsWithStatusRow, error) {
	rows, err := q.db.Query(ctx, getPastContractsWithStatus, arg.Status, arg.GuildID, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPastContractsWithStatusRow
	for rows.Next() {
		var i GetPastContractsWithStatusRow
		if err := rows.Scan(
			&i.ContractHistoryID,
			&i.GuildID,
			&i.ContractID,
			&i.Title,
			&i.OccurredAt,
			&i.Status,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertContractHistory = `-- name: InsertContractHistory :exec
INSERT INTO contract_history (
guild_id,
contract_id,
party_id,
difficulty,
status
) VALUES ($1, $2, $3, $4, $5)
`

type InsertContractHistoryParams struct {
	GuildID    uuid.UUID          `json:"guild_id"`
	ContractID uuid.UUID          `json:"contract_id"`
	PartyID    uuid.UUID          `json:"party_id"`
	Difficulty int32              `json:"difficulty"`
	Status     ContractStatusEnum `json:"status"`
}

func (q *Queries) InsertContractHistory(ctx context.Context, arg InsertContractHistoryParams) error {
	_, err := q.db.Exec(ctx, insertContractHistory,
		arg.GuildID,
		arg.ContractID,
		arg.PartyID,
		arg.Difficulty,
		arg.Status,
	)
	return err
}
