// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guilds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getCurrentRank = `-- name: GetCurrentRank :one
SELECT current_rank
FROM guilds
WHERE id = $1
`

func (q *Queries) GetCurrentRank(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getCurrentRank, id)
	var current_rank int32
	err := row.Scan(&current_rank)
	return current_rank, err
}

const getGuild = `-- name: GetGuild :one
SELECT
id,
current_rank,
treasury
FROM guilds
WHERE id =$1
`

type GetGuildRow struct {
	ID          uuid.UUID `json:"id"`
	CurrentRank int32     `json:"current_rank"`
	Treasury    int32     `json:"treasury"`
}

func (q *Queries) GetGuild(ctx context.Context, id uuid.UUID) (GetGuildRow, error) {
	row := q.db.QueryRow(ctx, getGuild, id)
	var i GetGuildRow
	err := row.Scan(&i.ID, &i.CurrentRank, &i.Treasury)
	return i, err
}

const getGuildTreasury = `-- name: GetGuildTreasury :one
SELECT treasury
FROM guilds
WHERE id = $1
`

func (q *Queries) GetGuildTreasury(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getGuildTreasury, id)
	var treasury int32
	err := row.Scan(&treasury)
	return treasury, err
}

const getRecruitmentSlots = `-- name: GetRecruitmentSlots :one
SELECT recruitment_slots
FROM guilds
WHERE id = $1
`

func (q *Queries) GetRecruitmentSlots(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getRecruitmentSlots, id)
	var recruitment_slots int32
	err := row.Scan(&recruitment_slots)
	return recruitment_slots, err
}

const insertGuild = `-- name: InsertGuild :one
INSERT INTO guilds (
	name 
) values($1) 
ON CONFLICT DO UPDATE
SET name = excluded.name
RETURNING id, name, created_at, updated_at, recruitment_slots, treasury, current_rank
`

func (q *Queries) InsertGuild(ctx context.Context, name string) (Guild, error) {
	row := q.db.QueryRow(ctx, insertGuild, name)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecruitmentSlots,
		&i.Treasury,
		&i.CurrentRank,
	)
	return i, err
}

const setGuildRank = `-- name: SetGuildRank :one
UPDATE guilds
SET current_rank = $2
WHERE id = $1
RETURNING id, name, created_at, updated_at, recruitment_slots, treasury, current_rank
`

type SetGuildRankParams struct {
	ID          uuid.UUID `json:"id"`
	CurrentRank int32     `json:"current_rank"`
}

func (q *Queries) SetGuildRank(ctx context.Context, arg SetGuildRankParams) (Guild, error) {
	row := q.db.QueryRow(ctx, setGuildRank, arg.ID, arg.CurrentRank)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecruitmentSlots,
		&i.Treasury,
		&i.CurrentRank,
	)
	return i, err
}

const setRecruitmentSlots = `-- name: SetRecruitmentSlots :one
UPDATE guilds
SET recruitment_slots = $2
WHERE id = $1
RETURNING id, name, created_at, updated_at, recruitment_slots, treasury, current_rank
`

type SetRecruitmentSlotsParams struct {
	ID               uuid.UUID `json:"id"`
	RecruitmentSlots int32     `json:"recruitment_slots"`
}

func (q *Queries) SetRecruitmentSlots(ctx context.Context, arg SetRecruitmentSlotsParams) (Guild, error) {
	row := q.db.QueryRow(ctx, setRecruitmentSlots, arg.ID, arg.RecruitmentSlots)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecruitmentSlots,
		&i.Treasury,
		&i.CurrentRank,
	)
	return i, err
}

const updateTreasury = `-- name: UpdateTreasury :one
UPDATE guilds
SET treasury = treasury + $2
WHERE id = $1
RETURNING id, name, created_at, updated_at, recruitment_slots, treasury, current_rank
`

type UpdateTreasuryParams struct {
	ID       uuid.UUID `json:"id"`
	Treasury int32     `json:"treasury"`
}

func (q *Queries) UpdateTreasury(ctx context.Context, arg UpdateTreasuryParams) (Guild, error) {
	row := q.db.QueryRow(ctx, updateTreasury, arg.ID, arg.Treasury)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecruitmentSlots,
		&i.Treasury,
		&i.CurrentRank,
	)
	return i, err
}
