// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guilds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getCurrentRank = `-- name: GetCurrentRank :one
SELECT current_rank
FROM guilds
WHERE id = $1
`

func (q *Queries) GetCurrentRank(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getCurrentRank, id)
	var current_rank int32
	err := row.Scan(&current_rank)
	return current_rank, err
}

const getGuildByID = `-- name: GetGuildByID :one
SELECT
id,
current_rank,
treasury
recruitment_slots,
current_rank
FROM guilds
WHERE id =$1
`

type GetGuildByIDRow struct {
	ID               uuid.UUID `json:"id"`
	CurrentRank      int32     `json:"current_rank"`
	RecruitmentSlots int32     `json:"recruitment_slots"`
	CurrentRank_2    int32     `json:"current_rank_2"`
}

func (q *Queries) GetGuildByID(ctx context.Context, id uuid.UUID) (GetGuildByIDRow, error) {
	row := q.db.QueryRow(ctx, getGuildByID, id)
	var i GetGuildByIDRow
	err := row.Scan(
		&i.ID,
		&i.CurrentRank,
		&i.RecruitmentSlots,
		&i.CurrentRank_2,
	)
	return i, err
}

const getGuildByName = `-- name: GetGuildByName :one
SELECT 
id,
current_rank,
treasury
recruitment_slots,
current_rank,
password
FROM guilds
WHERE name = $1
`

type GetGuildByNameRow struct {
	ID               uuid.UUID `json:"id"`
	CurrentRank      int32     `json:"current_rank"`
	RecruitmentSlots int32     `json:"recruitment_slots"`
	CurrentRank_2    int32     `json:"current_rank_2"`
	Password         string    `json:"password"`
}

func (q *Queries) GetGuildByName(ctx context.Context, name string) (GetGuildByNameRow, error) {
	row := q.db.QueryRow(ctx, getGuildByName, name)
	var i GetGuildByNameRow
	err := row.Scan(
		&i.ID,
		&i.CurrentRank,
		&i.RecruitmentSlots,
		&i.CurrentRank_2,
		&i.Password,
	)
	return i, err
}

const getGuildTreasury = `-- name: GetGuildTreasury :one
SELECT treasury
FROM guilds
WHERE id = $1
`

func (q *Queries) GetGuildTreasury(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getGuildTreasury, id)
	var treasury int32
	err := row.Scan(&treasury)
	return treasury, err
}

const getRecruitmentSlots = `-- name: GetRecruitmentSlots :one
SELECT recruitment_slots
FROM guilds
WHERE id = $1
`

func (q *Queries) GetRecruitmentSlots(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getRecruitmentSlots, id)
	var recruitment_slots int32
	err := row.Scan(&recruitment_slots)
	return recruitment_slots, err
}

const insertGuild = `-- name: InsertGuild :one
INSERT INTO guilds (
	name,
	password
) values($1, $2) 
ON CONFLICT DO UPDATE
SET password = excluded.password
RETURNING id, name, password, created_at, updated_at, recruitment_slots, treasury, current_rank
`

type InsertGuildParams struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

func (q *Queries) InsertGuild(ctx context.Context, arg InsertGuildParams) (Guild, error) {
	row := q.db.QueryRow(ctx, insertGuild, arg.Name, arg.Password)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecruitmentSlots,
		&i.Treasury,
		&i.CurrentRank,
	)
	return i, err
}

const setGuildRank = `-- name: SetGuildRank :exec
UPDATE guilds
SET current_rank = $2
WHERE id = $1
RETURNING id, name, password, created_at, updated_at, recruitment_slots, treasury, current_rank
`

type SetGuildRankParams struct {
	ID          uuid.UUID `json:"id"`
	CurrentRank int32     `json:"current_rank"`
}

func (q *Queries) SetGuildRank(ctx context.Context, arg SetGuildRankParams) error {
	_, err := q.db.Exec(ctx, setGuildRank, arg.ID, arg.CurrentRank)
	return err
}

const setRecruitmentSlots = `-- name: SetRecruitmentSlots :exec
UPDATE guilds
SET recruitment_slots = $2
WHERE id = $1
RETURNING id, name, password, created_at, updated_at, recruitment_slots, treasury, current_rank
`

type SetRecruitmentSlotsParams struct {
	ID               uuid.UUID `json:"id"`
	RecruitmentSlots int32     `json:"recruitment_slots"`
}

func (q *Queries) SetRecruitmentSlots(ctx context.Context, arg SetRecruitmentSlotsParams) error {
	_, err := q.db.Exec(ctx, setRecruitmentSlots, arg.ID, arg.RecruitmentSlots)
	return err
}

const updateTreasury = `-- name: UpdateTreasury :exec
UPDATE guilds
SET treasury = treasury + $2
WHERE id = $1
RETURNING id, name, password, created_at, updated_at, recruitment_slots, treasury, current_rank
`

type UpdateTreasuryParams struct {
	ID       uuid.UUID `json:"id"`
	Treasury int32     `json:"treasury"`
}

func (q *Queries) UpdateTreasury(ctx context.Context, arg UpdateTreasuryParams) error {
	_, err := q.db.Exec(ctx, updateTreasury, arg.ID, arg.Treasury)
	return err
}
