// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityEnum string

const (
	ActivityEnumAvailable  ActivityEnum = "available"
	ActivityEnumOnContract ActivityEnum = "on_contract"
	ActivityEnumSickLeave  ActivityEnum = "sick_leave"
	ActivityEnumRetired    ActivityEnum = "retired"
	ActivityEnumDead       ActivityEnum = "dead"
)

func (e *ActivityEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityEnum(s)
	case string:
		*e = ActivityEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityEnum: %T", src)
	}
	return nil
}

type NullActivityEnum struct {
	ActivityEnum ActivityEnum `json:"activity_enum"`
	Valid        bool         `json:"valid"` // Valid is true if ActivityEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityEnum), nil
}

type ContractStatusEnum string

const (
	ContractStatusEnumAvailable  ContractStatusEnum = "available"
	ContractStatusEnumInProgress ContractStatusEnum = "in-progress"
	ContractStatusEnumComplete   ContractStatusEnum = "complete"
	ContractStatusEnumFailed     ContractStatusEnum = "failed"
)

func (e *ContractStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContractStatusEnum(s)
	case string:
		*e = ContractStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ContractStatusEnum: %T", src)
	}
	return nil
}

type NullContractStatusEnum struct {
	ContractStatusEnum ContractStatusEnum `json:"contract_status_enum"`
	Valid              bool               `json:"valid"` // Valid is true if ContractStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContractStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ContractStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContractStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContractStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContractStatusEnum), nil
}

type RoleEnum string

const (
	RoleEnumFrontline   RoleEnum = "frontline"
	RoleEnumSpellcaster RoleEnum = "spellcaster"
	RoleEnumHealer      RoleEnum = "healer"
	RoleEnumGeneralist  RoleEnum = "generalist"
)

func (e *RoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleEnum(s)
	case string:
		*e = RoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleEnum: %T", src)
	}
	return nil
}

type NullRoleEnum struct {
	RoleEnum RoleEnum `json:"role_enum"`
	Valid    bool     `json:"valid"` // Valid is true if RoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleEnum), nil
}

type Adventurer struct {
	ID              uuid.UUID        `json:"id"`
	GuildID         pgtype.UUID      `json:"guild_id"`
	PartyID         pgtype.UUID      `json:"party_id"`
	JoinedAt        pgtype.Timestamp `json:"joined_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	CurrentRank     int32            `json:"current_rank"`
	CurrentActivity ActivityEnum     `json:"current_activity"`
	Name            pgtype.Text      `json:"name"`
	Description     string           `json:"description"`
	Role            RoleEnum         `json:"role"`
	UpkeepCost      int32            `json:"upkeep_cost"`
	RecruitmentCost int32            `json:"recruitment_cost"`
}

type AdventurerContractHistory struct {
	ID           uuid.UUID          `json:"id"`
	AdventurerID uuid.UUID          `json:"adventurer_id"`
	ContractID   uuid.UUID          `json:"contract_id"`
	Status       ContractStatusEnum `json:"status"`
	OccurredAt   pgtype.Timestamp   `json:"occurred_at"`
}

type AdventurerHistory struct {
	ID           uuid.UUID        `json:"id"`
	AdventurerID uuid.UUID        `json:"adventurer_id"`
	PartyID      pgtype.UUID      `json:"party_id"`
	OccurredAt   pgtype.Timestamp `json:"occurred_at"`
	Activity     ActivityEnum     `json:"activity"`
}

type Contract struct {
	ID               uuid.UUID          `json:"id"`
	GuildID          uuid.UUID          `json:"guild_id"`
	Title            pgtype.Text        `json:"title"`
	Difficulty       int32              `json:"difficulty"`
	MinimumPartySize int32              `json:"minimum_party_size"`
	Description      pgtype.Text        `json:"description"`
	ContractStatus   ContractStatusEnum `json:"contract_status"`
	Reward           int32              `json:"reward"`
	CreatedAt        pgtype.Timestamp   `json:"created_at"`
	UpdatedAt        pgtype.Timestamp   `json:"updated_at"`
}

type ContractHistory struct {
	ID         uuid.UUID          `json:"id"`
	GuildID    uuid.UUID          `json:"guild_id"`
	PartyID    uuid.UUID          `json:"party_id"`
	ContractID uuid.UUID          `json:"contract_id"`
	Difficulty int32              `json:"difficulty"`
	OccurredAt pgtype.Timestamp   `json:"occurred_at"`
	Status     ContractStatusEnum `json:"status"`
}

type Guild struct {
	ID               uuid.UUID        `json:"id"`
	Name             string           `json:"name"`
	Password         string           `json:"password"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	RecruitmentSlots int32            `json:"recruitment_slots"`
	Treasury         int32            `json:"treasury"`
	CurrentRank      int32            `json:"current_rank"`
}

type Party struct {
	ID               uuid.UUID        `json:"id"`
	ContractID       uuid.UUID        `json:"contract_id"`
	GuildID          uuid.UUID        `json:"guild_id"`
	Name             string           `json:"name"`
	PartyRank        int32            `json:"party_rank"`
	MaximumPartySize int32            `json:"maximum_party_size"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type PartyHistory struct {
	ID             uuid.UUID          `json:"id"`
	PartyID        uuid.UUID          `json:"party_id"`
	ContractID     uuid.UUID          `json:"contract_id"`
	OccuredAt      pgtype.Timestamp   `json:"occured_at"`
	ContractStatus ContractStatusEnum `json:"contract_status"`
}
