// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parties.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addpartyToContract = `-- name: AddpartyToContract :exec
Update parties
SET contract_id = $2
WHERE id = $1
`

type AddpartyToContractParams struct {
	ID         uuid.UUID   `json:"id"`
	ContractID pgtype.UUID `json:"contract_id"`
}

func (q *Queries) AddpartyToContract(ctx context.Context, arg AddpartyToContractParams) error {
	_, err := q.db.Exec(ctx, addpartyToContract, arg.ID, arg.ContractID)
	return err
}

const countMemberCompleteContracts = `-- name: CountMemberCompleteContracts :one
SELECT ach.adventurer_id, a.name, a.current_rank, COUNT(*) AS completed_count
FROM adventurer_contract_history ach
JOIN adventurers a ON a.id = ach.adventurer_id
JOIN contracts c ON ach.contract_id = c.id
WHERE ach.adventurer_id = $1
AND c.difficulty >= a.current_rank
AND ach.status = 'complete'
GROUP BY ach.adventurer_id, a.name, a.current_rank
`

type CountMemberCompleteContractsRow struct {
	AdventurerID   uuid.UUID   `json:"adventurer_id"`
	Name           pgtype.Text `json:"name"`
	CurrentRank    int32       `json:"current_rank"`
	CompletedCount int64       `json:"completed_count"`
}

func (q *Queries) CountMemberCompleteContracts(ctx context.Context, adventurerID uuid.UUID) (CountMemberCompleteContractsRow, error) {
	row := q.db.QueryRow(ctx, countMemberCompleteContracts, adventurerID)
	var i CountMemberCompleteContractsRow
	err := row.Scan(
		&i.AdventurerID,
		&i.Name,
		&i.CurrentRank,
		&i.CompletedCount,
	)
	return i, err
}

const createParty = `-- name: CreateParty :one
INSERT INTO parties (guild_id, name)
VALUES($1, $2)
RETURNING id, contract_id, guild_id, name, party_rank, maximum_party_size, party_status, created_at
`

type CreatePartyParams struct {
	GuildID uuid.UUID `json:"guild_id"`
	Name    string    `json:"name"`
}

func (q *Queries) CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, createParty, arg.GuildID, arg.Name)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.GuildID,
		&i.Name,
		&i.PartyRank,
		&i.MaximumPartySize,
		&i.PartyStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getAllParties = `-- name: GetAllParties :many
SELECT 
p.id AS party_id,
c.id AS contract_id,
c.title,
c.contract_status,
a.name,
a.role,
a.current_activity
FROM parties p
JOIN contracts c ON p.contract_id = c.id
JOIN adventurers a ON p.id = a.party_id
WHERE p.guild_id = $1
`

type GetAllPartiesRow struct {
	PartyID         uuid.UUID          `json:"party_id"`
	ContractID      uuid.UUID          `json:"contract_id"`
	Title           pgtype.Text        `json:"title"`
	ContractStatus  ContractStatusEnum `json:"contract_status"`
	Name            pgtype.Text        `json:"name"`
	Role            RoleEnum           `json:"role"`
	CurrentActivity ActivityEnum       `json:"current_activity"`
}

func (q *Queries) GetAllParties(ctx context.Context, guildID uuid.UUID) ([]GetAllPartiesRow, error) {
	rows, err := q.db.Query(ctx, getAllParties, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPartiesRow
	for rows.Next() {
		var i GetAllPartiesRow
		if err := rows.Scan(
			&i.PartyID,
			&i.ContractID,
			&i.Title,
			&i.ContractStatus,
			&i.Name,
			&i.Role,
			&i.CurrentActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberDetails = `-- name: GetMemberDetails :many
SELECT 
id
name,
role,
current_rank
FROM adventurers a
WHERE party_id = $1
`

type GetMemberDetailsRow struct {
	Name        uuid.UUID `json:"name"`
	Role        RoleEnum  `json:"role"`
	CurrentRank int32     `json:"current_rank"`
}

func (q *Queries) GetMemberDetails(ctx context.Context, partyID pgtype.UUID) ([]GetMemberDetailsRow, error) {
	rows, err := q.db.Query(ctx, getMemberDetails, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMemberDetailsRow
	for rows.Next() {
		var i GetMemberDetailsRow
		if err := rows.Scan(&i.Name, &i.Role, &i.CurrentRank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParty = `-- name: GetParty :one
SELECT
id,
guild_id,
contract_id,
party_rank,
name,
maximum_party_size
FROM parties
WHERE id = $1
`

type GetPartyRow struct {
	ID               uuid.UUID   `json:"id"`
	GuildID          uuid.UUID   `json:"guild_id"`
	ContractID       pgtype.UUID `json:"contract_id"`
	PartyRank        int32       `json:"party_rank"`
	Name             string      `json:"name"`
	MaximumPartySize int32       `json:"maximum_party_size"`
}

func (q *Queries) GetParty(ctx context.Context, id uuid.UUID) (GetPartyRow, error) {
	row := q.db.QueryRow(ctx, getParty, id)
	var i GetPartyRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.ContractID,
		&i.PartyRank,
		&i.Name,
		&i.MaximumPartySize,
	)
	return i, err
}

const getPartyDetails = `-- name: GetPartyDetails :many
SELECT 
p.id AS party_id,
c.title,
c.contract_status,
p.name,
p.party_rank,
a.id AS adventurer_id,
a.current_activity,
a.name,
a.role
FROM parties p
JOIN contracts c ON p.contract_id = c.id
JOIN adventurers a ON p.id = a.party_id
WHERE p.id = $1
`

type GetPartyDetailsRow struct {
	PartyID         uuid.UUID          `json:"party_id"`
	Title           pgtype.Text        `json:"title"`
	ContractStatus  ContractStatusEnum `json:"contract_status"`
	Name            string             `json:"name"`
	PartyRank       int32              `json:"party_rank"`
	AdventurerID    uuid.UUID          `json:"adventurer_id"`
	CurrentActivity ActivityEnum       `json:"current_activity"`
	Name_2          pgtype.Text        `json:"name_2"`
	Role            RoleEnum           `json:"role"`
}

func (q *Queries) GetPartyDetails(ctx context.Context, id uuid.UUID) ([]GetPartyDetailsRow, error) {
	rows, err := q.db.Query(ctx, getPartyDetails, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPartyDetailsRow
	for rows.Next() {
		var i GetPartyDetailsRow
		if err := rows.Scan(
			&i.PartyID,
			&i.Title,
			&i.ContractStatus,
			&i.Name,
			&i.PartyRank,
			&i.AdventurerID,
			&i.CurrentActivity,
			&i.Name_2,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMemberContractHistory = `-- name: InsertMemberContractHistory :many
INSERT INTO adventurer_contract_history(
adventurer_id,
contract_id,
status
)
SELECT
a.id,
c.id,
$2
FROM adventurers a
JOIN parties p ON a.party_id = p.id
WHERE p.contract_id = $1
RETURNING adventurer_id
`

type InsertMemberContractHistoryParams struct {
	ContractID pgtype.UUID        `json:"contract_id"`
	Status     ContractStatusEnum `json:"status"`
}

func (q *Queries) InsertMemberContractHistory(ctx context.Context, arg InsertMemberContractHistoryParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, insertMemberContractHistory, arg.ContractID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var adventurer_id uuid.UUID
		if err := rows.Scan(&adventurer_id); err != nil {
			return nil, err
		}
		items = append(items, adventurer_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPartyHistory = `-- name: InsertPartyHistory :exec
INSERT INTO party_history (
	party_id,
    contract_id,
	contract_status
) VALUES($1 , $2, $3)
`

type InsertPartyHistoryParams struct {
	PartyID        uuid.UUID          `json:"party_id"`
	ContractID     uuid.UUID          `json:"contract_id"`
	ContractStatus ContractStatusEnum `json:"contract_status"`
}

func (q *Queries) InsertPartyHistory(ctx context.Context, arg InsertPartyHistoryParams) error {
	_, err := q.db.Exec(ctx, insertPartyHistory, arg.PartyID, arg.ContractID, arg.ContractStatus)
	return err
}

const removePartyFromContract = `-- name: RemovePartyFromContract :exec
UPDATE parties
SET contract_id = NULL
WHERE id = $1
`

func (q *Queries) RemovePartyFromContract(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, removePartyFromContract, id)
	return err
}

const setMemberStatus = `-- name: SetMemberStatus :exec
UPDATE adventurers
SET current_activity = $1
WHERE party_id = (
    SELECT id 
    FROM parties 
    WHERE contract_id = $2
)
`

type SetMemberStatusParams struct {
	CurrentActivity ActivityEnum `json:"current_activity"`
	ContractID      pgtype.UUID  `json:"contract_id"`
}

func (q *Queries) SetMemberStatus(ctx context.Context, arg SetMemberStatusParams) error {
	_, err := q.db.Exec(ctx, setMemberStatus, arg.CurrentActivity, arg.ContractID)
	return err
}

const setPartyRank = `-- name: SetPartyRank :exec
UPDATE parties
SET party_rank = $1
WHERE id = $2
`

type SetPartyRankParams struct {
	PartyRank int32     `json:"party_rank"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SetPartyRank(ctx context.Context, arg SetPartyRankParams) error {
	_, err := q.db.Exec(ctx, setPartyRank, arg.PartyRank, arg.ID)
	return err
}
