// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parties.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createParty = `-- name: CreateParty :one
INSERT INTO parties (guild_id, contract_id, name)
VALUES($1, $2, $3)
RETURNING id, contract_id, name, guild_id, maximum_party_size, created_at
`

type CreatePartyParams struct {
	GuildID    uuid.UUID `json:"guild_id"`
	ContractID uuid.UUID `json:"contract_id"`
	Name       string    `json:"name"`
}

func (q *Queries) CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, createParty, arg.GuildID, arg.ContractID, arg.Name)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.ContractID,
		&i.Name,
		&i.GuildID,
		&i.MaximumPartySize,
		&i.CreatedAt,
	)
	return i, err
}

const getAllParties = `-- name: GetAllParties :many
SELECT 
p.id AS party_id,
c.id AS contract_id,
c.title,
c.contract_status,
a.name,
a.role,
a.current_activity
FROM parties p
JOIN contracts c ON p.contract_id = c.id
JOIN party_members pm ON p.id = pm.party_id
JOIN adventurers a ON pm.adventurer_id = a.id
WHERE p.guild_id = $1
`

type GetAllPartiesRow struct {
	PartyID         uuid.UUID          `json:"party_id"`
	ContractID      uuid.UUID          `json:"contract_id"`
	Title           pgtype.Text        `json:"title"`
	ContractStatus  ContractStatusEnum `json:"contract_status"`
	Name            pgtype.Text        `json:"name"`
	Role            RoleEnum           `json:"role"`
	CurrentActivity ActivityEnum       `json:"current_activity"`
}

func (q *Queries) GetAllParties(ctx context.Context, guildID uuid.UUID) ([]GetAllPartiesRow, error) {
	rows, err := q.db.Query(ctx, getAllParties, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPartiesRow
	for rows.Next() {
		var i GetAllPartiesRow
		if err := rows.Scan(
			&i.PartyID,
			&i.ContractID,
			&i.Title,
			&i.ContractStatus,
			&i.Name,
			&i.Role,
			&i.CurrentActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartyDetails = `-- name: GetPartyDetails :many
SELECT 
p.id AS party_id,
c.title,
c.contract_status,
a.id AS adventurer_id,
a.current_activity,
a.name,
a.role
FROM parties p
JOIN contracts c ON p.contract_id = c.id
JOIN party_members pm ON pm.party_id = p.id
JOIN adventurers a ON a.id = pm.adventurer_id
WHERE p.id = $1
`

type GetPartyDetailsRow struct {
	PartyID         uuid.UUID          `json:"party_id"`
	Title           pgtype.Text        `json:"title"`
	ContractStatus  ContractStatusEnum `json:"contract_status"`
	AdventurerID    uuid.UUID          `json:"adventurer_id"`
	CurrentActivity ActivityEnum       `json:"current_activity"`
	Name            pgtype.Text        `json:"name"`
	Role            RoleEnum           `json:"role"`
}

func (q *Queries) GetPartyDetails(ctx context.Context, id uuid.UUID) ([]GetPartyDetailsRow, error) {
	rows, err := q.db.Query(ctx, getPartyDetails, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPartyDetailsRow
	for rows.Next() {
		var i GetPartyDetailsRow
		if err := rows.Scan(
			&i.PartyID,
			&i.Title,
			&i.ContractStatus,
			&i.AdventurerID,
			&i.CurrentActivity,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
